TOP=../..

include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE
#=============================

#=============================
# Build the IOC application

PROD_IOC = arcus
# arcus.dbd will be created and installed
DBD += arcus.dbd

# arcus.dbd will be made up from these files:
arcus_DBD += base.dbd
arcus_DBD += modules.dbd

# Include dbd files from all support applications:
#arcus_DBD += xxx.dbd

# Add all the support libraries needed by this IOC
#arcus_LIBS += xxx

# arcus_registerRecordDeviceDriver.cpp derives from arcus.dbd
arcus_SRCS += arcus_registerRecordDeviceDriver.cpp

# Build the main IOC entry point on workstation OSs.
arcus_SRCS_DEFAULT += arcusMain.cpp
arcus_SRCS_vxWorks += -nil-

# Add support from base/src/vxWorks if needed
#arcus_OBJS_vxWorks += $(EPICS_BASE_BIN)/vxComLibrary

# Finally link to the EPICS Base libraries
arcus_LIBS += $(EPICS_BASE_IOC_LIBS)
arcus_LIBS += pvaSrv pvAccess pvData pvMB

#===========================

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
PROD_LIBS += stream
PROD_LIBS += asyn
